import{useMemo,useRef,useState}from'react';
import*as XLSX from'xlsx';
import{Download,FileSpreadsheet,Upload,ShoppingCart,AlertTriangle,Search,CheckCircle2}from'lucide-react';
import PageHeader from'../components/PageHeader';
import DataTable from'../components/DataTable';
import{Field}from'../components/FormGrid';
import{useApp}from'../context/AppContext';
import{currency,num,statusOf}from'../utils/costs';
import{exportExcel}from'../utils/exporters';
import{classifyItem}from'../utils/itemClassifier';

const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const pick=(row,names)=>{const keys=Object.keys(row);for(const n of names){const k=keys.find(x=>norm(x)===norm(n));if(k!==undefined)return row[k]}return''};
const toNum=v=>{if(v===''||v===null||v===undefined)return 0;const n=Number(String(v).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const makeCsv=(rows)=>{const header=['codigo','nome','categoria','subcategoria','quantidade','reservado','unidade','valor_unitario','valor_medio','fornecedor','estoque_minimo','aplicacao','status'];const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const body=rows.map(i=>[i.code,i.name,i.category,i.subcategory,i.qty,i.reserved,i.unit,i.unitCost,i.avgCost,i.supplier,i.min,i.application,statusOf(i)].map(esc).join(';'));return [header.join(';'),...body].join('\n')};
const downloadFile=(name,content,type='text/csv;charset=utf-8')=>{const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
const stamp=()=>new Date().toISOString().slice(0,19).replace(/[T:]/g,'-');

export default function Productivity(){const{stock,upsertStock,notify,createPurchaseSuggestion,totals,exportSafetyBackup,dbHealth,machines,machineCosts}=useApp();const inputRef=useRef(null);const[preview,setPreview]=useState([]);const[mode,setMode]=useState('atualizar-adicionar');const[query,setQuery]=useState('');
 const stockRows=useMemo(()=>stock.map(i=>({codigo:i.code,nome:i.name,categoria:i.category,subcategoria:i.subcategory,quantidade:i.qty,reservado:i.reserved,disponivel:num(i.qty)-num(i.reserved),unidade:i.unit,valor_unitario:i.unitCost,valor_medio:i.avgCost,valor_total:num(i.qty)*num(i.avgCost||i.unitCost),fornecedor:i.supplier,estoque_minimo:i.min,aplicacao:i.application,status:statusOf(i)})),[stock]);
 const lowRows=useMemo(()=>totals.low.filter(i=>`${i.code} ${i.name} ${i.category}`.toLowerCase().includes(query.toLowerCase())).map(i=>({id:i.id,codigo:i.code,nome:i.name,atual:i.qty,minimo:i.min||'',reservado:i.reserved||0,comprar:Math.max(((i.min===''||i.min===null||i.min===undefined)?0:num(i.min))+num(i.reserved)-num(i.qty),1),unidade:i.unit,valor:currency(num(i.avgCost||i.unitCost)),status:statusOf(i)})),[totals.low,query]);
 const noValue=useMemo(()=>stock.filter(i=>num(i.unitCost||i.avgCost)<=0).length,[stock]);
 const noMin=useMemo(()=>stock.filter(i=>i.min===''||i.min===null||i.min===undefined).length,[stock]);
 const exportComplete=()=>exportExcel(`estoque-completo-${stamp()}`,stockRows);
 const exportCsv=()=>downloadFile(`estoque-completo-${stamp()}.csv`,makeCsv(stock));
 const exportPurchaseList=()=>exportExcel(`lista-compra-estoque-minimo-${stamp()}`,lowRows);
 const exportCostByMachine=()=>exportExcel(`custo-por-maquina-${stamp()}`,machineCosts.map(m=>({codigo:m.machine.code,maquina:m.machine.name,modelo:m.machine.model,custo:m.total,preco:m.price,lucro:m.profitValue,margem:m.margin,itens:m.items?.length||0})));
 const handleFile=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});const mapped=rows.map((r,idx)=>{const name=pick(r,['nome','nome do item','item','produto','descricao','descrição']);const code=pick(r,['codigo','código','code']);const smart=classifyItem(name,stock);return{_linha:idx+2,code:String(code||smart.code||'').trim(),name:String(name||'').trim(),category:String(pick(r,['categoria'])||smart.category||'Estoque').trim(),subcategory:String(pick(r,['subcategoria','sub-categoria'])||smart.subcategory||'Geral').trim(),qty:toNum(pick(r,['quantidade','qtd','estoque','estoque atual'])),reserved:toNum(pick(r,['reservado','reserva'])),unit:String(pick(r,['unidade','unid','un'])||smart.unit||'un').trim(),unitCost:toNum(pick(r,['valor unitario','valor unitário','v. unitário','unitcost','preco','preço'])),avgCost:toNum(pick(r,['valor medio','valor médio','custo medio','custo médio']))||toNum(pick(r,['valor unitario','valor unitário','v. unitário','preco','preço'])),supplier:String(pick(r,['fornecedor'])||'').trim(),min:pick(r,['estoque minimo','estoque mínimo','minimo','mínimo'])===''?'':toNum(pick(r,['estoque minimo','estoque mínimo','minimo','mínimo'])),application:String(pick(r,['aplicacao','aplicação','uso'])||smart.application||'Estoque geral').trim()}}).filter(r=>r.name);setPreview(mapped);notify(`${mapped.length} item(ns) carregados para conferência`)}catch(err){console.error(err);notify('Não consegui ler essa planilha/CSV','error')}};
 const applyImport=()=>{if(!preview.length)return notify('Carregue uma planilha primeiro','error');if(!window.confirm(`Importar ${preview.length} item(ns)? Nada será apagado. Um backup será baixado antes.`))return;exportSafetyBackup('antes-importar-estoque-produtividade');let added=0,updated=0;preview.forEach(row=>{const existing=stock.find(i=>String(i.code||'').trim().toUpperCase()===String(row.code||'').trim().toUpperCase())||stock.find(i=>String(i.name||'').trim().toUpperCase()===String(row.name||'').trim().toUpperCase());if(existing){updated++;if(mode==='somente-novos')return;upsertStock({...existing,...row,id:existing.id})}else{added++;upsertStock(row)}});notify(`Importação concluída. Novos: ${added}. Atualizados: ${mode==='somente-novos'?0:updated}.`);setPreview([]);if(inputRef.current)inputRef.current.value=''};
 const suggestAllPurchases=()=>{if(!lowRows.length)return notify('Nenhum item abaixo do mínimo');if(!window.confirm(`Gerar sugestões de compra para ${lowRows.length} item(ns)?`))return;totals.low.forEach(createPurchaseSuggestion);notify('Sugestões de compra geradas')};
 const smartStats=[{label:'Itens no estoque',value:stock.length},{label:'Abaixo do mínimo',value:totals.low.length},{label:'Sem valor',value:noValue},{label:'Sem mínimo',value:noMin},{label:'Máquinas cadastradas',value:machines.length},{label:'Saúde: vínculos quebrados',value:dbHealth.brokenBom}];
 return <><PageHeader title="Produtividade" subtitle="Exportação, importação segura, compras por estoque mínimo e relatórios rápidos" actions={<><button className="btn-ghost" onClick={exportCsv}><Download size={18}/>CSV</button><button className="btn-primary" onClick={exportComplete}><FileSpreadsheet size={18}/>Excel completo</button></>}/>
 <div className="mb-5 grid gap-3 md:grid-cols-6">{smartStats.map(s=><div className="card" key={s.label}><p className="text-xs font-semibold uppercase text-brand-steel dark:text-white/60">{s.label}</p><p className="mt-1 text-2xl font-semibold">{s.value}</p></div>)}</div>
 <div className="grid gap-5 xl:grid-cols-2"><section className="card"><h3 className="text-xl font-semibold">Exportações rápidas</h3><p className="mt-1 text-sm text-brand-steel dark:text-white/60">Gere arquivos de segurança e análise sem mexer no banco.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><button className="btn-primary" onClick={exportComplete}><FileSpreadsheet size={18}/>Estoque completo Excel</button><button className="btn-ghost" onClick={exportCsv}><Download size={18}/>Estoque completo CSV</button><button className="btn-ghost" onClick={exportPurchaseList}><ShoppingCart size={18}/>Lista de compra</button><button className="btn-ghost" onClick={exportCostByMachine}><FileSpreadsheet size={18}/>Custo por máquina</button></div></section>
 <section className="card"><h3 className="text-xl font-semibold">Importar estoque por Excel/CSV</h3><p className="mt-1 text-sm text-brand-steel dark:text-white/60">Seguro: atualiza/adiciona e não apaga nenhum item.</p><div className="mt-4 grid gap-3"><Field label="Modo de importação" value={mode} options={[{value:'atualizar-adicionar',label:'Atualizar existentes e adicionar novos'},{value:'somente-novos',label:'Adicionar somente novos'}]} onChange={setMode}/><input ref={inputRef} className="input" type="file" accept=".xlsx,.xls,.csv" onChange={handleFile}/><button className="btn-warning" onClick={applyImport}><Upload size={18}/>Importar conferidos</button></div></section></div>
 <section className="card mt-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-semibold">Compras por estoque mínimo</h3><p className="text-sm text-brand-steel dark:text-white/60">Filtre, exporte ou gere sugestões de compra para itens críticos.</p></div><div className="flex flex-wrap gap-2"><button className="btn-ghost" onClick={exportPurchaseList}><Download size={18}/>Exportar lista</button><button className="btn-primary" onClick={suggestAllPurchases}><ShoppingCart size={18}/>Gerar compras</button></div></div><label className="mb-4 flex items-center gap-3"><Search size={18}/><input className="flex-1 bg-transparent outline-none" placeholder="Buscar item crítico..." value={query} onChange={e=>setQuery(e.target.value)}/></label><DataTable rows={lowRows} columns={[{key:'codigo',label:'Código'},{key:'nome',label:'Item'},{key:'atual',label:'Atual'},{key:'minimo',label:'Mínimo'},{key:'comprar',label:'Comprar'},{key:'unidade',label:'Un.'},{key:'valor',label:'Valor un.'},{key:'status',label:'Status',render:r=><span className={`badge ${r.status==='Em falta'?'bg-brand-red text-white':'bg-brand-yellow text-brand-black'}`}>{r.status}</span>}]} empty="Nenhum item abaixo do mínimo."/></section>
 {preview.length>0&&<section className="card mt-5 border-brand-yellow"><div className="mb-4 flex items-center gap-2"><AlertTriangle size={18}/><h3 className="text-xl font-semibold">Prévia da importação</h3></div><p className="mb-4 text-sm text-brand-steel dark:text-white/60">Confira antes de aplicar. A importação não apaga nenhum item.</p><DataTable rows={preview.slice(0,80)} columns={[{key:'_linha',label:'Linha'},{key:'code',label:'Código'},{key:'name',label:'Nome'},{key:'category',label:'Categoria'},{key:'qty',label:'Qtd'},{key:'unit',label:'Un.'},{key:'unitCost',label:'Valor'}]}/>{preview.length>80&&<p className="mt-3 text-sm text-brand-steel">Mostrando 80 de {preview.length} itens.</p>}<button className="btn-primary mt-4" onClick={applyImport}><CheckCircle2 size={18}/>Confirmar importação</button></section>}
 </>}
