import{useMemo,useState}from'react';
import{useSearchParams,Link}from'react-router-dom';
import{ArrowDown,ArrowUp,Camera,CheckCircle2,PackageSearch,QrCode,Search}from'lucide-react';
import PageHeader from'../components/PageHeader';
import{Field}from'../components/FormGrid';
import{useApp}from'../context/AppContext';
import{availableOf,statusOf}from'../utils/costs';

const colaboradores=['Vinicius','Luciano','Bruno','Gabriel','Sidney','Hanyel','Robson','Julia','Carla'];

export default function QuickMovement(){
 const{stock,quickMove,notify,movements}=useApp();const[params,setParams]=useSearchParams();const[itemId,setItemId]=useState(params.get('item')||'');const[query,setQuery]=useState('');const[type,setType]=useState('saída');const[qty,setQty]=useState(1);const[worker,setWorker]=useState('');const[use,setUse]=useState('');const[scanning,setScanning]=useState(false);
 const item=stock.find(i=>i.id===itemId);
 const matches=useMemo(()=>query?stock.filter(i=>`${i.code} ${i.name} ${i.location||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,20):[],[query,stock]);
 const itemHistory=useMemo(()=>item?movements.filter(m=>m.item===item.name).slice(0,8):[],[movements,item]);
 const choose=i=>{setItemId(i.id);setParams({item:i.id});setQuery('')};
 const submit=()=>{if(!item)return notify('Escolha um item','error');if(!worker.trim())return notify('Informe o colaborador','error');quickMove({productId:item.id,type,qty,reason:`${worker}${use?` • ${use}`:''}`});setQty(1)};
 const tryScan=async()=>{setScanning(true);notify('Leitor de QR aberto. Aponte para a etiqueta.');try{if(!('BarcodeDetector'in window))throw new Error('Leitor nativo não disponível neste navegador');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const video=document.createElement('video');video.srcObject=stream;video.playsInline=true;await video.play();const detector=new window.BarcodeDetector({formats:['qr_code']});let tries=0;const tick=async()=>{tries++;const codes=await detector.detect(video);if(codes?.[0]?.rawValue){stream.getTracks().forEach(t=>t.stop());setScanning(false);const url=new URL(codes[0].rawValue,location.origin);const id=url.searchParams.get('item');const found=stock.find(i=>i.id===id);if(found){choose(found);notify('QR Code identificado');return}notify('QR Code não corresponde a um item','error');return}if(tries<120)setTimeout(tick,250);else{stream.getTracks().forEach(t=>t.stop());setScanning(false);notify('Não consegui ler o QR Code','error')}};tick()}catch(e){setScanning(false);notify('Neste aparelho, use a câmera do celular para abrir o QR ou busque o item pelo nome','error')}};
 return <><PageHeader title="Movimentação rápida" subtitle="Tela simples para usar pelo celular via QR Code, retirada ou devolução" actions={<Link className="btn-ghost" to="/estoque"><PackageSearch size={18}/>Estoque</Link>}/>
 <div className="grid gap-5 lg:grid-cols-[1fr,380px]"><section className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-semibold">Escolha o item</h3><button className="btn-warning" onClick={tryScan}><Camera size={18}/>{scanning?'Lendo QR...':'Ler QR Code'}</button></div><label className="mt-4 flex items-center gap-3 border border-brand-line p-3 dark:border-white/10"><Search size={18}/><input className="flex-1 bg-transparent outline-none" placeholder="Buscar item por nome, código ou localização..." value={query} onChange={e=>setQuery(e.target.value)}/></label>{matches.length>0&&<div className="mt-3 max-h-72 overflow-auto border border-brand-line dark:border-white/10">{matches.map(i=><button key={i.id} onClick={()=>choose(i)} className="grid w-full grid-cols-[1fr,90px] gap-2 border-b border-brand-line p-3 text-left text-sm hover:bg-brand-light dark:border-white/10 dark:hover:bg-white/10"><span><b>{i.name}</b><br/><span className="text-xs text-brand-steel">{i.code} • {i.location||'sem localização'}</span></span><span className="text-right font-semibold">{i.qty} {i.unit}</span></button>)}</div>}{item&&<div className="mt-5 grid gap-3 md:grid-cols-4"><div className="card md:col-span-2"><p className="text-xs uppercase text-brand-steel">Item selecionado</p><h2 className="text-2xl font-semibold">{item.name}</h2><p className="font-mono text-sm">{item.code}</p></div><div className="card"><p className="text-xs uppercase text-brand-steel">Atual</p><p className="text-2xl font-semibold">{item.qty} {item.unit}</p></div><div className="card"><p className="text-xs uppercase text-brand-steel">Disponível</p><p className="text-2xl font-semibold">{availableOf(item)} {item.unit}</p></div></div>}</section>
 <section className="card"><h3 className="text-xl font-semibold">Registrar</h3><div className="mt-4 grid gap-3"><Field label="Tipo" value={type} options={[{value:'saída',label:'Retirar'},{value:'devolução',label:'Devolver'},{value:'entrada',label:'Entrada'}]} onChange={setType}/><Field label="Quantidade" type="number" min="1" step="1" value={qty} onChange={setQty}/><Field label="Colaborador" value={worker} options={['',...colaboradores]} onChange={setWorker}/><Field label="Uso / Máquina / Observação" value={use} placeholder="Ex: ENCHE PALHEIROS / manutenção" onChange={setUse}/><button className="btn-primary" onClick={submit}>{type==='saída'?<ArrowDown size={18}/>:<ArrowUp size={18}/>}Confirmar {type}</button></div>{item&&<div className="mt-4 rounded-none border border-brand-line p-3 text-sm dark:border-white/10"><p><b>Status:</b> {statusOf(item)}</p><p><b>Local:</b> {item.location||'Não informado'}</p></div>}</section></div>
 {item&&<section className="card mt-5"><h3 className="mb-3 flex items-center gap-2 text-xl font-semibold"><CheckCircle2 size={18}/>Últimas movimentações deste item</h3>{itemHistory.length?itemHistory.map(m=><div key={m.id} className="grid gap-1 border-b border-brand-line py-2 text-sm dark:border-white/10"><b>{m.type} • {m.qty}</b><span className="text-brand-steel dark:text-white/60">{m.date} {m.time} • {m.reason||'-'}</span></div>):<p className="text-sm text-brand-steel">Sem histórico ainda.</p>}</section>}
 </>}
