import{createContext,useContext,useEffect,useMemo,useRef,useState}from'react';
import{bomSeed,machinesSeed,maintenanceSeed,movementsSeed,opsSeed,purchasesSeed,stockSeed,suppliersSeed}from'../data/seed';
import{useLocalStorage}from'../hooks/useLocalStorage';
import{isSupabaseConfigured}from'../services/supabaseClient';
import{deleteCollectionItem,loadAllCollections,loadCollection,replaceCollection,upsertCollectionItem,uppercaseStockNames,saveDailyCloudBackup}from'../services/databaseService';
import{availableOf,calcMachineCost,num,statusOf,today}from'../utils/costs';
import{downloadJson}from'../utils/exporters';

const Ctx=createContext(null);const rid=()=>crypto.randomUUID();const nowTime=()=>new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const collections=['stock','machines','bom','suppliers','movements','purchases','ops','maintenance','warranties','soldMachines'];

export function AppProvider({children}){
 const[stockRaw,setStockRaw]=useLocalStorage('gift.stock.v4',stockSeed);
 const[machinesRaw,setMachinesRaw]=useLocalStorage('gift.machines.v4',machinesSeed);
 const[bomRaw,setBomRaw]=useLocalStorage('gift.bom.v4',bomSeed);
 const[suppliersRaw,setSuppliersRaw]=useLocalStorage('gift.suppliers.v4',suppliersSeed);
 const[movementsRaw,setMovementsRaw]=useLocalStorage('gift.movements.v4',movementsSeed);
 const[purchasesRaw,setPurchasesRaw]=useLocalStorage('gift.purchases.v4',purchasesSeed);
 const[opsRaw,setOpsRaw]=useLocalStorage('gift.ops.v4',opsSeed);
 const[maintenanceRaw,setMaintenanceRaw]=useLocalStorage('gift.maintenance.v4',maintenanceSeed);
 const[warrantiesRaw,setWarrantiesRaw]=useLocalStorage('gift.warranties.v1',[]);
 const[soldMachinesRaw,setSoldMachinesRaw]=useLocalStorage('gift.soldMachines.v1',[]);
 const[settings,setSettings]=useLocalStorage('gift.settings.v4',{dark:false,user:'Administrador',logo:'/logo-gift.png'});
 const[auth,setAuth]=useLocalStorage('gift.auth.v4',{logged:false});
 const[backupSettings,setBackupSettings]=useLocalStorage('gift.backup.settings.v1',{dailyEnabled:true,lastDailyBackupDate:'',lastDailyBackupAt:''});
 const[toast,setToast]=useState(null);
 const[dbStatus,setDbStatus]=useState(isSupabaseConfigured?'Conectando ao Supabase':'Modo local');
 const loadedRef=useRef(!isSupabaseConfigured);
 const settersRef=useRef({});
 const statesRef=useRef({});

 const notify=(message,type='ok')=>{setToast({message,type});setTimeout(()=>setToast(null),2600)};
 const showDbError=e=>{console.error(e);setDbStatus('Erro no Supabase');notify(`Erro no Supabase: ${e.message||e}`,'error')};
 const makeBackupSnapshot=(tipo='backup')=>({stock:statesRef.current.stock||stockRaw,machines:statesRef.current.machines||machinesRaw,bom:statesRef.current.bom||bomRaw,suppliers:statesRef.current.suppliers||suppliersRaw,movements:statesRef.current.movements||movementsRaw,purchases:statesRef.current.purchases||purchasesRaw,ops:statesRef.current.ops||opsRaw,maintenance:statesRef.current.maintenance||maintenanceRaw,warranties:statesRef.current.warranties||warrantiesRaw,soldMachines:statesRef.current.soldMachines||soldMachinesRaw,settings,createdAt:new Date().toISOString(),tipo});
 const exportSafetyBackup=(label='seguranca')=>{const stamp=new Date().toISOString().replace(/[:.]/g,'-');downloadJson(`backup-${label}-${stamp}.json`,makeBackupSnapshot('backup manual/seguranca'))};
 const runDailyBackupIfNeeded=async(force=false)=>{if(!backupSettings?.dailyEnabled&&!force)return;const todayKey=new Date().toISOString().slice(0,10);if(!force&&backupSettings?.lastDailyBackupDate===todayKey)return;const snapshot=makeBackupSnapshot('backup diario automatico em nuvem');try{if(isSupabaseConfigured){await saveDailyCloudBackup(force?'backup-diario-forcado':'backup-diario-automatico',snapshot);setBackupSettings({...backupSettings,lastDailyBackupDate:todayKey,lastDailyBackupAt:new Date().toISOString(),lastDailyBackupMode:'Supabase'});if(force)notify('Backup diário salvo no Supabase');return;}localStorage.setItem(`gift.daily.backup.${todayKey}`,JSON.stringify(snapshot));setBackupSettings({...backupSettings,lastDailyBackupDate:todayKey,lastDailyBackupAt:new Date().toISOString(),lastDailyBackupMode:'Navegador'});if(force)notify('Backup diário salvo no navegador');}catch(e){console.error('Backup diario em nuvem',e);if(force)notify(`Erro ao salvar backup diário: ${e.message||e}`,'error');throw e}};
 const strongConfirm=(title,phrase)=>{const msg=`${title}\n\nDigite exatamente: ${phrase}`;return window.prompt(msg)==phrase};
 const persist=(collection,rows)=>{if(!isSupabaseConfigured||!loadedRef.current)return;if(['stock','movements'].includes(collection))return;if(['machines','bom'].includes(collection)&&Array.isArray(rows)&&rows.length===0)return;replaceCollection(collection,rows).catch(showDbError)};
 const makeSetter=(collection,baseSetter)=>update=>baseSetter(prev=>{const next=typeof update==='function'?update(prev):update;statesRef.current[collection]=next;persist(collection,next);return next});
 const setStock=makeSetter('stock',setStockRaw);const setMachines=makeSetter('machines',setMachinesRaw);const setBom=makeSetter('bom',setBomRaw);const setSuppliers=makeSetter('suppliers',setSuppliersRaw);const setMovements=makeSetter('movements',setMovementsRaw);const setPurchases=makeSetter('purchases',setPurchasesRaw);const setOps=makeSetter('ops',setOpsRaw);const setMaintenance=makeSetter('maintenance',setMaintenanceRaw);const setWarranties=makeSetter('warranties',setWarrantiesRaw);const setSoldMachines=makeSetter('soldMachines',setSoldMachinesRaw);
 settersRef.current={stock:setStockRaw,machines:setMachinesRaw,bom:setBomRaw,suppliers:setSuppliersRaw,movements:setMovementsRaw,purchases:setPurchasesRaw,ops:setOpsRaw,maintenance:setMaintenanceRaw,warranties:setWarrantiesRaw,soldMachines:setSoldMachinesRaw};
 statesRef.current={stock:stockRaw,machines:machinesRaw,bom:bomRaw,suppliers:suppliersRaw,movements:movementsRaw,purchases:purchasesRaw,ops:opsRaw,maintenance:maintenanceRaw,warranties:warrantiesRaw,soldMachines:soldMachinesRaw};

 useEffect(()=>{let active=true;if(!isSupabaseConfigured)return;setDbStatus('Conectando ao Supabase');loadAllCollections().then(data=>{if(!active)return;loadedRef.current=false;collections.forEach(key=>{settersRef.current[key](data[key]||[]);statesRef.current[key]=data[key]||[]});loadedRef.current=true;setDbStatus('Supabase conectado')}).catch(e=>{loadedRef.current=true;showDbError(e)});return()=>{active=false}},[]);

 useEffect(()=>{if(!auth?.logged)return;const timer=setTimeout(()=>{runDailyBackupIfNeeded().catch(e=>console.error('Backup diario automatico',e))},1800);return()=>clearTimeout(timer)},[auth?.logged,backupSettings?.dailyEnabled,backupSettings?.lastDailyBackupDate,stockRaw.length,machinesRaw.length,bomRaw.length]);

 useEffect(()=>{if(!isSupabaseConfigured)return;let active=true;const refresh=async()=>{if(!loadedRef.current)return;try{const [nextStock,nextMovements]=await Promise.all([loadCollection('stock'),loadCollection('movements')]);if(!active)return;settersRef.current.stock(nextStock||[]);settersRef.current.movements(nextMovements||[]);statesRef.current.stock=nextStock||[];statesRef.current.movements=nextMovements||[]}catch(e){console.error('Auto refresh Supabase',e)}};const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer)}},[]);

 const visible=x=>x?.archived!==true&&x?.archived!=='true';const stock=stockRaw.filter(visible),machines=machinesRaw.filter(visible),bom=bomRaw.filter(visible),suppliers=suppliersRaw,movements=movementsRaw.filter(visible),purchases=purchasesRaw,ops=opsRaw,maintenance=maintenanceRaw,warranties=warrantiesRaw,soldMachines=soldMachinesRaw;
 const addMovement=m=>{const mv={id:rid('mv'),date:today(),time:nowTime(),createdAt:new Date().toISOString(),user:settings.user,...m};setMovements(v=>[mv,...v]);if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('movements',mv).catch(showDbError)};
 const upsertStock=item=>{const isNew=!item?.id;const oldItem=item?.id?stock.find(i=>i.id===item.id):null;const clean={...item,application:item.application||'Estoque geral',qty:Math.max(0,num(item.qty)),reserved:Math.max(0,num(item.reserved)),unitCost:Math.max(0,num(item.unitCost)),avgCost:Math.max(0,num(item.avgCost||item.unitCost)),min:(item.min===''||item.min===null||item.min===undefined)?'':Math.max(0,num(item.min))};clean.status=statusOf(clean);if(!clean.id)clean.id=rid('p');setStock(s=>clean.id?s.some(i=>i.id===clean.id)?s.map(i=>i.id===clean.id?clean:i):[clean,...s]:[clean,...s]);if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('stock',clean).catch(showDbError);if(isNew){addMovement({type:num(clean.qty)>0?'entrada':'cadastro de item',item:clean.name,qty:num(clean.qty),reason:'Cadastro inicial do item',op:''})}else if(oldItem){const changes=[];['name','code','category','subcategory','unit','unitCost','avgCost','min','supplier','application','location','photoUrl','attachments','toolResponsible','toolStatus','qty','reserved'].forEach(k=>{if(String(oldItem[k]??'')!==String(clean[k]??''))changes.push(`${k}: ${oldItem[k]??''} → ${clean[k]??''}`)});if(changes.length)addMovement({type:'alteração de item',item:clean.name,qty:0,reason:changes.slice(0,6).join(' | ')+(changes.length>6?' | ...':''),op:''})}};
 const deleteStock=id=>{const item=stock.find(i=>i.id===id);if(!item)return;const links=bom.filter(l=>l.productId===id).length;const phrase=(item.code||item.name||'EXCLUIR').toString().toUpperCase();const title=`ATENÇÃO: excluir item do estoque\n\nItem: ${item.name}\nCódigo: ${item.code||'-'}\nQtd atual: ${item.qty||0}\nMáquinas vinculadas: ${links}\n\nAntes de excluir, um backup JSON será baixado automaticamente.`;if(!strongConfirm(title,phrase)){notify('Exclusão cancelada','error');return}exportSafetyBackup('antes-excluir-item');addMovement({type:'item removido',item:item.name,qty:num(item.qty),reason:`Item deletado do estoque com confirmação forte. Vínculos: ${links}`,op:''});setStock(s=>s.filter(i=>i.id!==id));if(isSupabaseConfigured&&loadedRef.current)deleteCollectionItem('stock',id).catch(showDbError)};
 const quickMove=({productId,type,qty,reason,op=''})=>{const q=num(qty);const p=stock.find(i=>i.id===productId);if(!p||q<=0)return notify('Movimentação inválida','error');let next={...p};if(type==='entrada'){const oldTotal=num(p.qty)*num(p.avgCost||p.unitCost);const cost=num(p.unitCost);next.qty=num(p.qty)+q;next.avgCost=(oldTotal+q*cost)/(next.qty||1)}else if(type==='saída'||type==='perda'){if(availableOf(p)<q)return notify('Estoque disponível insuficiente','error');next.qty=num(p.qty)-q}else if(type==='devolução'){next.qty=num(p.qty)+q}else if(type==='transferência'){}else if(type==='reserva produção'){if(availableOf(p)<q)return notify('Disponível insuficiente para reservar','error');next.reserved=num(p.reserved)+q}else if(type==='baixa reserva'){if(num(p.reserved)<q)return notify('Reserva insuficiente','error');next.reserved=num(p.reserved)-q;next.qty=num(p.qty)-q}next.status=statusOf(next);setStock(s=>s.map(i=>i.id===p.id?next:i));if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('stock',next).catch(showDbError);addMovement({type,item:p.name,qty:q,reason,op});notify('Movimentação registrada')};
 const reserveOP=opId=>{const op=ops.find(o=>o.id===opId);const machine=machines.find(m=>m.id===op?.machineId);if(!op||!machine)return;const lines=bom.filter(l=>l.machineId===machine.id);const missing=lines.map(l=>({l,p:stock.find(i=>i.id===l.productId)})).filter(x=>!x.p||availableOf(x.p)<num(x.l.qty));if(missing.length){notify('Existem materiais insuficientes para reservar','error');return false}lines.forEach(l=>quickMove({productId:l.productId,type:'reserva produção',qty:l.qty,reason:`Reserva ${op.number}`,op:op.number}));const next=ops.map(x=>x.id===opId?{...x,status:'Materiais reservados',progress:40,startedAt:today()}:x);setOps(next);return true};
 const finishOP=opId=>{const op=ops.find(o=>o.id===opId);const machine=machines.find(m=>m.id===op?.machineId);if(!op||!machine)return;const lines=bom.filter(l=>l.machineId===machine.id);const missing=lines.map(l=>({l,p:stock.find(i=>i.id===l.productId)})).filter(x=>!x.p||num(x.p.reserved)<num(x.l.qty));if(missing.length){notify('Faça a reserva antes de finalizar','error');return}lines.forEach(l=>quickMove({productId:l.productId,type:'baixa reserva',qty:l.qty,reason:`Baixa ${op.number}`,op:op.number}));const cost=calcMachineCost(machine,bom,stock).total;setOps(o=>o.map(x=>x.id===opId?{...x,status:'Finalizada',progress:100,finishedAt:today(),realCost:cost}:x));notify('OP finalizada e estoque baixado')};
 const deleteOP=opId=>{const op=ops.find(o=>o.id===opId);if(!op)return;const machine=machines.find(m=>m.id===op.machineId);if(machine&&!['Finalizada','Cancelada'].includes(op.status)){const lines=bom.filter(l=>l.machineId===machine.id);const ids=new Set(lines.map(l=>l.productId));setStock(s=>s.map(item=>{if(!ids.has(item.id))return item;const qty=lines.filter(l=>l.productId===item.id).reduce((a,l)=>a+num(l.qty),0);const next={...item,reserved:Math.max(0,num(item.reserved)-qty)};next.status=statusOf(next);if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('stock',next).catch(showDbError);return next}));lines.forEach(l=>addMovement({type:'cancelamento reserva',item:stock.find(i=>i.id===l.productId)?.name||'Item',qty:num(l.qty),reason:`Remoção ${op.number}`,op:op.number}))}setOps(o=>o.filter(x=>x.id!==opId));if(isSupabaseConfigured&&loadedRef.current)deleteCollectionItem('ops',opId).catch(showDbError);notify('OP removida')};
 const createPurchaseSuggestion=item=>{const buy=Math.max(((item.min===''||item.min===null||item.min===undefined)?0:num(item.min))+num(item.reserved)-num(item.qty),1);const pc={id:rid('pc'),number:`PC-${String(purchases.length+1).padStart(4,'0')}`,supplier:item.supplier,status:'Sugerido',eta:'',value:buy*num(item.avgCost||item.unitCost),items:[{productId:item.id,qty:buy,unitCost:num(item.avgCost||item.unitCost)}],notes:'Gerado por estoque mínimo'};setPurchases(p=>[pc,...p]);if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('purchases',pc).catch(showDbError);notify('Pedido de compra sugerido')};
 const receivePurchase=id=>{const pc=purchases.find(p=>p.id===id);if(!pc)return;pc.items?.forEach(it=>quickMove({productId:it.productId,type:'entrada',qty:it.qty,reason:`Recebimento ${pc.number}`}));setPurchases(ps=>ps.map(p=>p.id===id?{...p,status:'Recebido',receivedAt:today()}:p));notify('Compra recebida no estoque')};
 const backup=()=>downloadJson('backup-almoxarifado-gift.json',{stock,machines,bom,suppliers,movements,purchases,ops,maintenance,warranties,soldMachines,settings,createdAt:new Date().toISOString()});
 const restore=data=>{exportSafetyBackup('antes-importar-backup');if(data.stock)setStock(data.stock);if(data.machines)setMachines(data.machines);if(data.bom)setBom(data.bom);if(data.suppliers)setSuppliers(data.suppliers);if(data.movements)setMovements(data.movements);if(data.purchases)setPurchases(data.purchases);if(data.ops)setOps(data.ops);if(data.maintenance)setMaintenance(data.maintenance);if(data.warranties)setWarranties(data.warranties);if(data.soldMachines)setSoldMachines(data.soldMachines);notify('Backup restaurado')};
 const resetDemo=()=>{const phrase='EU CONFIRMO ZERAR';if(!strongConfirm('AÇÃO PERIGOSA: zerar dados do sistema. Um backup JSON será baixado antes de limpar.',phrase)){notify('Zerar dados cancelado','error');return}exportSafetyBackup('antes-zerar-dados');setStock([]);setMachines([]);setBom([]);setSuppliers([]);setMovements([]);setPurchases([]);setOps([]);setMaintenance([]);setWarranties([]);setSoldMachines([]);notify('Sistema zerado com backup de segurança')};
 const uppercaseStockItemNames=async()=>{if(!isSupabaseConfigured)return notify('Supabase não configurado','error');try{exportSafetyBackup('antes-maiusculo-estoque');setDbStatus('Padronizando estoque...');const result=await uppercaseStockNames();const nextStock=await loadCollection('stock');settersRef.current.stock(nextStock||[]);statesRef.current.stock=nextStock||[];setDbStatus('Supabase conectado');notify(`Nomes padronizados em maiúsculo. Itens alterados: ${result?.total_updated??0}`)}catch(e){showDbError(e)}};

 const duplicateGroups=useMemo(()=>{const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[-_]/g,' ').replace(/\s+/g,' ').trim().toUpperCase();const byCode=new Map(),byName=new Map(),byMachine=new Map();stock.forEach(i=>{const c=norm(i.code);const n=norm(i.name);if(c)byCode.set(c,[...(byCode.get(c)||[]),i]);if(n)byName.set(n,[...(byName.get(n)||[]),i])});machines.forEach(m=>{let k=norm(`${m.name||''} ${m.model||''}`);k=k.replace(/BATE TURBO|TURBO|VIBRO MASTER|VIBROMASTER|MODELO|MAQUINA|MÁQUINA/g,'').replace(/\s+/g,' ').trim();if(k)byMachine.set(k,[...(byMachine.get(k)||[]),m])});const pairs=map=>[...map.entries()].filter(([,v])=>v.length>1).map(([key,items])=>({key,items}));return{codes:pairs(byCode),names:pairs(byName),machines:pairs(byMachine)}} ,[stock,machines]);
 const archived={stock:stockRaw.filter(i=>i?.archived===true||i?.archived==='true'),machines:machinesRaw.filter(i=>i?.archived===true||i?.archived==='true'),bom:bomRaw.filter(i=>i?.archived===true||i?.archived==='true')};
 const brokenBom=useMemo(()=>{const stockIds=new Set(stock.map(i=>i.id));const machineIds=new Set(machines.map(m=>m.id));return bomRaw.filter(l=>l?.archived!==true&&l?.archived!=='true'&&(!stockIds.has(l.productId)||!machineIds.has(l.machineId))).map(l=>({...l,itemName:stockRaw.find(i=>i.id===l.productId)?.name||'Item não encontrado',machineName:machinesRaw.find(m=>m.id===l.machineId)?.name||'Máquina não encontrada'}))},[bomRaw,stock,stockRaw,machines,machinesRaw]);
 const archiveStockItem=id=>{const item=stockRaw.find(i=>i.id===id);if(!item)return;exportSafetyBackup('antes-arquivar-item');const next={...item,archived:true,archivedAt:new Date().toISOString(),archivedReason:'Arquivado pela tela Organização'};setStock(s=>s.map(i=>i.id===id?next:i));if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('stock',next).catch(showDbError);addMovement({type:'item arquivado',item:item.name,qty:num(item.qty),reason:'Arquivado sem excluir do banco',op:''});notify('Item arquivado')};
 const restoreStockItem=id=>{const item=stockRaw.find(i=>i.id===id);if(!item)return;const next={...item,archived:false,restoredAt:new Date().toISOString()};setStock(s=>s.map(i=>i.id===id?next:i));if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('stock',next).catch(showDbError);addMovement({type:'item restaurado',item:item.name,qty:num(item.qty),reason:'Restaurado da lixeira',op:''});notify('Item restaurado')};
 const archiveMachine=id=>{const item=machinesRaw.find(i=>i.id===id);if(!item)return;exportSafetyBackup('antes-arquivar-maquina');const next={...item,archived:true,archivedAt:new Date().toISOString(),archivedReason:'Arquivada pela tela Organização'};setMachines(s=>s.map(i=>i.id===id?next:i));if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('machines',next).catch(showDbError);addMovement({type:'máquina arquivada',item:item.name,qty:0,reason:`Modelo: ${item.model||'-'}`,op:''});notify('Máquina arquivada')};
 const restoreMachine=id=>{const item=machinesRaw.find(i=>i.id===id);if(!item)return;const next={...item,archived:false,restoredAt:new Date().toISOString()};setMachines(s=>s.map(i=>i.id===id?next:i));if(isSupabaseConfigured&&loadedRef.current)upsertCollectionItem('machines',next).catch(showDbError);addMovement({type:'máquina restaurada',item:item.name,qty:0,reason:`Modelo: ${item.model||'-'}`,op:''});notify('Máquina restaurada')};
 const mergeMachines=(mainId,duplicateIds=[])=>{const main=machinesRaw.find(m=>m.id===mainId);const ids=[...new Set(duplicateIds)].filter(id=>id&&id!==mainId);if(!main||!ids.length)return notify('Escolha uma máquina principal e pelo menos uma duplicada','error');if(!window.confirm(`Mesclar ${ids.length} máquina(s) em ${main.name} / ${main.model||'-'}? Será baixado backup antes.`))return;exportSafetyBackup('antes-mesclar-maquinas');const when=new Date().toISOString();const nextBom=bomRaw.map(l=>ids.includes(l.machineId)?{...l,machineId:mainId,mergedFrom:l.machineId,mergedAt:when}:l);const nextMachines=machinesRaw.map(m=>ids.includes(m.id)?{...m,archived:true,mergedInto:mainId,archivedAt:when,archivedReason:`Mesclada em ${main.name} / ${main.model||'-'}`}:m);setBom(nextBom);setMachines(nextMachines);if(isSupabaseConfigured&&loadedRef.current){Promise.all([...nextBom.filter(l=>ids.includes(l.mergedFrom)).map(l=>upsertCollectionItem('bom',l)),...nextMachines.filter(m=>ids.includes(m.id)).map(m=>upsertCollectionItem('machines',m))]).catch(showDbError)}addMovement({type:'mesclagem de máquinas',item:main.name,qty:ids.length,reason:`Duplicadas mescladas/arquivadas: ${ids.join(', ')}`,op:''});notify('Máquinas mescladas com segurança')};
 const cleanBrokenBom=()=>{if(!brokenBom.length)return notify('Nenhum vínculo quebrado encontrado');if(!window.confirm(`Arquivar ${brokenBom.length} vínculo(s) quebrado(s) da estrutura? Será baixado backup antes.`))return;exportSafetyBackup('antes-limpar-vinculos-quebrados');const ids=new Set(brokenBom.map(l=>l.id));const when=new Date().toISOString();const next=bomRaw.map(l=>ids.has(l.id)?{...l,archived:true,archivedAt:when,archivedReason:'Vínculo quebrado arquivado pela tela Organização'}:l);setBom(next);if(isSupabaseConfigured&&loadedRef.current)Promise.all(next.filter(l=>ids.has(l.id)).map(l=>upsertCollectionItem('bom',l))).catch(showDbError);notify('Vínculos quebrados arquivados')};
 const totals=useMemo(()=>{const items=stock.reduce((a,i)=>a+num(i.qty),0);const reserved=stock.reduce((a,i)=>a+num(i.reserved),0);const available=stock.reduce((a,i)=>a+availableOf(i),0);const value=stock.reduce((a,i)=>a+num(i.qty)*num(i.avgCost||i.unitCost),0);const low=stock.filter(i=>statusOf(i)!=='OK');return{items,reserved,available,value,low}},[stock]);
 const machineCosts=useMemo(()=>machines.map(m=>({machine:m,...calcMachineCost(m,bom,stock)})),[machines,bom,stock]);
 const dbHealth=useMemo(()=>{const codes=new Map();stock.forEach(i=>{const c=(i.code||'').trim().toUpperCase();if(c)codes.set(c,(codes.get(c)||0)+1)});const machineKeys=new Map();machines.forEach(m=>{const k=`${(m.name||'').replace(/[-_]/g,' ').trim().toUpperCase()}|${(m.model||'').replace(/[-_]/g,' ').trim().toUpperCase()}`;machineKeys.set(k,(machineKeys.get(k)||0)+1)});const stockIds=new Set(stock.map(i=>i.id));const machineIds=new Set(machines.map(m=>m.id));return{items:stock.length,withoutCode:stock.filter(i=>!String(i.code||'').trim()).length,withoutName:stock.filter(i=>!String(i.name||'').trim()).length,withoutValue:stock.filter(i=>num(i.unitCost||i.avgCost)<=0).length,withoutCategory:stock.filter(i=>!String(i.category||'').trim()).length,withoutUnit:stock.filter(i=>!String(i.unit||'').trim()).length,withoutMin:stock.filter(i=>i.min===''||i.min===null||i.min===undefined).length,duplicateCodes:[...codes.values()].filter(v=>v>1).length,duplicateMachines:[...machineKeys.values()].filter(v=>v>1).length,brokenBom:bom.filter(l=>!stockIds.has(l.productId)||!machineIds.has(l.machineId)).length,archivedItems:stockRaw.filter(i=>i?.archived===true||i?.archived==='true').length,archivedMachines:machinesRaw.filter(i=>i?.archived===true||i?.archived==='true').length,movements:movements.length};},[stock,machines,bom,movements,stockRaw,machinesRaw]);
 const value={stock,stockRaw,setStock,upsertStock,deleteStock,archiveStockItem,restoreStockItem,quickMove,addMovement,machines,machinesRaw,setMachines,archiveMachine,restoreMachine,mergeMachines,bom,bomRaw,setBom,brokenBom,cleanBrokenBom,duplicateGroups,archived,suppliers,setSuppliers,movements,setMovements,purchases,setPurchases,receivePurchase,createPurchaseSuggestion,ops,setOps,reserveOP,finishOP,deleteOP,maintenance,setMaintenance,warranties,setWarranties,soldMachines,setSoldMachines,settings,setSettings,auth,setAuth,toast,notify,totals,machineCosts,backup,restore,resetDemo,uppercaseStockItemNames,exportSafetyBackup,backupSettings,setBackupSettings,runDailyBackupIfNeeded,dbHealth,rid,dbStatus,isSupabaseConfigured};return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export const useApp=()=>useContext(Ctx);
